changelog:
  exclude:
    authors:
      - dependabot
      - red-hat-konflux[bot]
      - openshift-merge-bot[bot]
      - RHTAS-build-bot
  categories:
    - title: Fixes
      labels:
        - bug
    - title: Features
      labels:
        - enhancement
    - title: Other
      labels:
        - "*"
