---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rhtas-redhat-com-v1alpha2-ctlog
  failurePolicy: Fail
  name: mctlog.kb.io
  rules:
  - apiGroups:
    - rhtas.redhat.com
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - ctlogs
  sideEffects: None
