apiVersion: rhtas.redhat.com/v1alpha2
kind: CTlog
metadata:
  labels:
    app.kubernetes.io/name: ctlog
    app.kubernetes.io/instance: ctlog-sample
    app.kubernetes.io/part-of: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rhtas-operator
  name: ctlog-sample
spec:
  # TODO(user): Add fields here
