//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/securesign/operator/api"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlog) DeepCopyInto(out *CTlog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlog.
func (in *CTlog) DeepCopy() *CTlog {
	if in == nil {
		return nil
	}
	out := new(CTlog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CTlog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlogList) DeepCopyInto(out *CTlogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CTlog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlogList.
func (in *CTlogList) DeepCopy() *CTlogList {
	if in == nil {
		return nil
	}
	out := new(CTlogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CTlogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlogSpec) DeepCopyInto(out *CTlogSpec) {
	*out = *in
	if in.LogConfig != nil {
		in, out := &in.LogConfig, &out.LogConfig
		*out = make([]LogConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Monitoring = in.Monitoring
	in.Trillian.DeepCopyInto(&out.Trillian)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlogSpec.
func (in *CTlogSpec) DeepCopy() *CTlogSpec {
	if in == nil {
		return nil
	}
	out := new(CTlogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CTlogStatus) DeepCopyInto(out *CTlogStatus) {
	*out = *in
	if in.LogConfig != nil {
		in, out := &in.LogConfig, &out.LogConfig
		*out = make([]LogConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CTlogStatus.
func (in *CTlogStatus) DeepCopy() *CTlogStatus {
	if in == nil {
		return nil
	}
	out := new(CTlogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
	if in.RootsPemFile != nil {
		in, out := &in.RootsPemFile, &out.RootsPemFile
		*out = make([]api.SecretKeySelector, len(*in))
		copy(*out, *in)
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.PrivateKeyPasswordRef != nil {
		in, out := &in.PrivateKeyPasswordRef, &out.PrivateKeyPasswordRef
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.PublicKeyRef != nil {
		in, out := &in.PublicKeyRef, &out.PublicKeyRef
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.ExtKeyUsages != nil {
		in, out := &in.ExtKeyUsages, &out.ExtKeyUsages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotAfterStart != nil {
		in, out := &in.NotAfterStart, &out.NotAfterStart
		*out = (*in).DeepCopy()
	}
	if in.NotAfterLimit != nil {
		in, out := &in.NotAfterLimit, &out.NotAfterLimit
		*out = (*in).DeepCopy()
	}
	if in.FrozenSth != nil {
		in, out := &in.FrozenSth, &out.FrozenSth
		*out = new(SignedTreeHead)
		(*in).DeepCopyInto(*out)
	}
	if in.RejectExtensions != nil {
		in, out := &in.RejectExtensions, &out.RejectExtensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignedTreeHead) DeepCopyInto(out *SignedTreeHead) {
	*out = *in
	if in.Sha256RootHash != nil {
		in, out := &in.Sha256RootHash, &out.Sha256RootHash
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.TreeHeadSignature != nil {
		in, out := &in.TreeHeadSignature, &out.TreeHeadSignature
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignedTreeHead.
func (in *SignedTreeHead) DeepCopy() *SignedTreeHead {
	if in == nil {
		return nil
	}
	out := new(SignedTreeHead)
	in.DeepCopyInto(out)
	return out
}
